version: '3'

services:

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    networks:
    - local
    depends_on:
    - taskboard-server
    ports:
    - 80:8000
    - 443:9000
    volumes:
    - ./proxy-conf:/etc/nginx/conf.d
    - ./proxy-cert:/etc/nginx/cert

  taskboard-server:
    image: reboot-server
    networks:
    - local
    depends_on:
      - taskboard-sockets
    build:
      context: ./reboot-server
      dockerfile: Dockerfile

  taskboard-sockets:
    image: reboot-sockets
    networks:
    - local
    ports:
    - 5000:80
    build:
      context: ./reboot-sockets
      dockerfile: Dockerfile

networks:
   local: